authors = ["Fredrik Bagge Carlson <cont-frb@ulund.org>"]
name = "Savefig"
uuid = "dc0377b4-a942-11e8-0d1e-27a9b054b1a5"
version = "0.1.0"

[deps]

[compat]
julia = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
